# Generated by Django 3.2.7 on 2021-12-06 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutuals',
            name='is_following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutuals',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='mutual', to=settings.AUTH_USER_MODEL),
        ),
    ]
