# Generated by Django 3.2.7 on 2021-12-06 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211206_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutuals',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mutual', to=settings.AUTH_USER_MODEL),
        ),
    ]
