# Generated by Django 3.2.7 on 2021-12-10 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_mutual_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_followed',
            field=models.ManyToManyField(blank=True, related_name='_network_user_is_followed_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='mutual',
        ),
    ]
