# Generated by Django 3.2.7 on 2021-12-10 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211210_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_followed',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
