# Generated by Django 3.2.7 on 2021-12-06 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_mutuals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutuals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual', to=settings.AUTH_USER_MODEL),
        ),
    ]
