# Generated by Django 3.2.7 on 2021-12-10 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_is_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_followed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
